run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - ineffassign
    - deadcode
    - errcheck
    - gosimple
    - typecheck
    - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: smpp-simulator
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
